#pragma once

#include "GLFW/glfw3.h"

#define BOREAL_KEY_0 GLFW_KEY_0
#define BOREAL_KEY_1 GLFW_KEY_1
#define BOREAL_KEY_2 GLFW_KEY_2
#define BOREAL_KEY_3 GLFW_KEY_3
#define BOREAL_KEY_4 GLFW_KEY_4
#define BOREAL_KEY_5 GLFW_KEY_5
#define BOREAL_KEY_6 GLFW_KEY_6
#define BOREAL_KEY_7 GLFW_KEY_7
#define BOREAL_KEY_8 GLFW_KEY_8
#define BOREAL_KEY_9 GLFW_KEY_9
#define BOREAL_KEY_A GLFW_KEY_A
#define BOREAL_KEY_B GLFW_KEY_B
#define BOREAL_KEY_C GLFW_KEY_C
#define BOREAL_KEY_D GLFW_KEY_D
#define BOREAL_KEY_E GLFW_KEY_E
#define BOREAL_KEY_F GLFW_KEY_F
#define BOREAL_KEY_G GLFW_KEY_G
#define BOREAL_KEY_H GLFW_KEY_H
#define BOREAL_KEY_I GLFW_KEY_I
#define BOREAL_KEY_J GLFW_KEY_J
#define BOREAL_KEY_K GLFW_KEY_K
#define BOREAL_KEY_L GLFW_KEY_L
#define BOREAL_KEY_M GLFW_KEY_M
#define BOREAL_KEY_N GLFW_KEY_N
#define BOREAL_KEY_O GLFW_KEY_O
#define BOREAL_KEY_P GLFW_KEY_P
#define BOREAL_KEY_Q GLFW_KEY_Q
#define BOREAL_KEY_R GLFW_KEY_R
#define BOREAL_KEY_S GLFW_KEY_S
#define BOREAL_KEY_T GLFW_KEY_T
#define BOREAL_KEY_U GLFW_KEY_U
#define BOREAL_KEY_V GLFW_KEY_V
#define BOREAL_KEY_W GLFW_KEY_W
#define BOREAL_KEY_X GLFW_KEY_X
#define BOREAL_KEY_Y GLFW_KEY_Y
#define BOREAL_KEY_Z GLFW_KEY_Z
#define BOREAL_KEY_F GLFW_KEY_F
#define BOREAL_KEY_F1 GLFW_KEY_F1
#define BOREAL_KEY_F2 GLFW_KEY_F2
#define BOREAL_KEY_F3 GLFW_KEY_F3
#define BOREAL_KEY_F4 GLFW_KEY_F4
#define BOREAL_KEY_F5 GLFW_KEY_F5
#define BOREAL_KEY_F6 GLFW_KEY_F6
#define BOREAL_KEY_F7 GLFW_KEY_F7
#define BOREAL_KEY_F8 GLFW_KEY_F8
#define BOREAL_KEY_F9 GLFW_KEY_F9
#define BOREAL_KEY_F10 GLFW_KEY_F10
#define BOREAL_KEY_F11 GLFW_KEY_F11
#define BOREAL_KEY_F12 GLFW_KEY_F12
#define BOREAL_KEY_F13 GLFW_KEY_F13
#define BOREAL_KEY_F14 GLFW_KEY_F14
#define BOREAL_KEY_F15 GLFW_KEY_F15
#define BOREAL_KEY_F16 GLFW_KEY_F16
#define BOREAL_KEY_F17 GLFW_KEY_F17
#define BOREAL_KEY_F18 GLFW_KEY_F18
#define BOREAL_KEY_F19 GLFW_KEY_F19
#define BOREAL_KEY_F20 GLFW_KEY_F20
#define BOREAL_KEY_F21 GLFW_KEY_F21
#define BOREAL_KEY_F22 GLFW_KEY_F22
#define BOREAL_KEY_F23 GLFW_KEY_F23
#define BOREAL_KEY_F24 GLFW_KEY_F24
#define BOREAL_KEY_F25 GLFW_KEY_F25
#define BOREAL_KEY_ESCAPE GLFW_KEY_ESCAPE
#define BOREAL_KEY_DOWN GLFW_KEY_DOWN
#define BOREAL_KEY_UP GLFW_KEY_UP
#define BOREAL_KEY_LEFT GLFW_KEY_LEFT
#define BOREAL_KEY_RIGHT GLFW_KEY_RIGHT
#define BOREAL_KEY_APOSTROPHE GLFW_KEY_APOSTROPHE
#define BOREAL_KEY_BACKSLASH GLFW_KEY_BACKSLASH
#define BOREAL_KEY_BACKSPACE GLFW_KEY_BACKSPACE
#define BOREAL_KEY_CAPS_LOCK GLFW_KEY_CAPS_LOCK
#define BOREAL_KEY_COMMA GLFW_KEY_COMMA
#define BOREAL_KEY_DELETE GLFW_KEY_DELETE
#define BOREAL_KEY_END GLFW_KEY_END
#define BOREAL_KEY_ENTER GLFW_KEY_ENTER
#define BOREAL_KEY_EQUAL GLFW_KEY_EQUAL
#define BOREAL_KEY_GRAVE_ACCENT GLFW_KEY_GRAVE_ACCENT
#define BOREAL_KEY_LAST GLFW_KEY_LAST
#define BOREAL_KEY_LEFT GLFW_KEY_LEFT
#define BOREAL_KEY_LEFT_ALT GLFW_KEY_LEFT_ALT
#define BOREAL_KEY_LEFT_BRACKET GLFW_KEY_LEFT_BRACKET
#define BOREAL_KEY_LEFT_CONTROL GLFW_KEY_LEFT_CONTROL
#define BOREAL_KEY_LEFT_SHIFT GLFW_KEY_LEFT_SHIFT
#define BOREAL_KEY_LEFT_SUPER GLFW_KEY_LEFT_SUPER
#define BOREAL_KEY_RIGHT_ALT GLFW_KEY_RIGHT_ALT
#define BOREAL_KEY_RIGHT_BRACKET GLFW_KEY_RIGHT_BRACKET
#define BOREAL_KEY_RIGHT_CONTROL GLFW_KEY_RIGHT_CONTROL
#define BOREAL_KEY_RIGHT_SHIFT GLFW_KEY_RIGHT_SHIFT
#define BOREAL_KEY_RIGHT_SUPER GLFW_KEY_RIGHT_SUPER
#define BOREAL_KEY_MENU GLFW_KEY_MENU
#define BOREAL_KEY_MINUS GLFW_KEY_MINUS
#define BOREAL_KEY_NUM_LOCK GLFW_KEY_NUM_LOCK
#define BOREAL_KEY_PAGE_DOWN GLFW_KEY_PAGE_DOWN
#define BOREAL_KEY_PAGE_UP GLFW_KEY_PAGE_UP
#define BOREAL_KEY_PAUSE GLFW_KEY_PAUSE
#define BOREAL_KEY_PERIOD GLFW_KEY_PERIOD
#define BOREAL_KEY_PRINT_SCREEN GLFW_KEY_PRINT_SCREEN
#define BOREAL_KEY_HOME GLFW_KEY_HOME
#define BOREAL_KEY_SCROLL_LOCK GLFW_KEY_SCROLL_LOCK
#define BOREAL_KEY_SEMICOLON GLFW_KEY_SEMICOLON
#define BOREAL_KEY_SLASH GLFW_KEY_SLASH
#define BOREAL_KEY_SPACE GLFW_KEY_SPACE
#define BOREAL_KEY_TAB GLFW_KEY_TAB
#define BOREAL_KEY_UNKNOWN GLFW_KEY_UNKNOWN
#define BOREAL_KEY_WORLD_1 GLFW_KEY_WORLD_1
#define BOREAL_KEY_WORLD_2 GLFW_KEY_WORLD_2
#define BOREAL_KEY_KP_0 GLFW_KEY_KP_0
#define BOREAL_KEY_KP_1 GLFW_KEY_KP_1
#define BOREAL_KEY_KP_2 GLFW_KEY_KP_2
#define BOREAL_KEY_KP_3 GLFW_KEY_KP_3
#define BOREAL_KEY_KP_4 GLFW_KEY_KP_4
#define BOREAL_KEY_KP_5 GLFW_KEY_KP_5
#define BOREAL_KEY_KP_6 GLFW_KEY_KP_6
#define BOREAL_KEY_KP_7 GLFW_KEY_KP_7
#define BOREAL_KEY_KP_8 GLFW_KEY_KP_8
#define BOREAL_KEY_KP_9 GLFW_KEY_KP_9
#define BOREAL_KEY_KP_ADD GLFW_KEY_KP_ADD
#define BOREAL_KEY_KP_DECIMAL GLFW_KEY_KP_DECIMAL
#define BOREAL_KEY_KP_DIVIDE GLFW_KEY_KP_DIVIDE
#define BOREAL_KEY_KP_ENTER GLFW_KEY_KP_ENTER
#define BOREAL_KEY_KP_EQUAL GLFW_KEY_KP_EQUAL
#define BOREAL_KEY_KP_MULTIPLY GLFW_KEY_KP_MULTIPLY
#define BOREAL_KEY_KP_SUBTRACT GLFW_KEY_KP_SUBTRACT
#define BOREAL_PRESS GLFW_PRESS

namespace Boreal {
	/**
	* @brief Allows user to handle user input.
	*
	* @section DESCRIPTION
	*
	* The input class allows the user input to be read
	* The class consists of static functions only so no instantiation is required
	* 
	*/
	class Input {
	public:
		/**
		* @brief Update function to be used in main loop, polls for events
		*/
		static void Update() { glfwPollEvents(); }
	};
}